name: qftools
description: A comprehensive Flutter project management CLI tool for streamlining development workflows.
version: 1.0.3
homepage: https://github.com/vignarajj/qftools
repository: https://github.com/vignarajj/qftools

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  io: ^1.0.4
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

executables:
  qftools:
